name: Build SunamoStringJoinPairs

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoStringJoinPairs
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringJoinPairs/SunamoStringJoinPairs.csproj

    - name: Build
      run: dotnet build SunamoStringJoinPairs/SunamoStringJoinPairs.csproj --configuration Release --no-restore

  test:
    name: Test SunamoStringJoinPairs.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringJoinPairs.Tests/SunamoStringJoinPairs.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoStringJoinPairs.Tests/SunamoStringJoinPairs.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoStringJoinPairs.Tests/SunamoStringJoinPairs.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
